### ISSUE TITLE
babel-plugin-react-intl: extractFromFormatMessageCall crashes on function parameter destructuring

### ISSUE THREAD

**Issue by nstepien** [formatjs/formatjs#1632]
**Which package?**
`babel-plugin-react-intl`

**Describe the bug**
I have a function that looks like this:
```
function myFunction(param1, { formatMessage, formatDate }) {
```
and is called like this:
```
const child = myFunction(filterable, intl);
```
and I get an error like this when trying to parse it:
```
TypeError: xxx\lib\components\MyComponent.js: Cannot read property '0' of undefined
    at isFormatMessageDestructuring (xxx\client\node_modules\babel-plugin-react-intl\dist\index.js:166:50)
    at isFormatMessageCall (xxx\client\node_modules\babel-plugin-react-intl\dist\index.js:174:9)
    at PluginPass.CallExpression (xxx\client\node_modules\babel-plugin-react-intl\dist\index.js:412:53)
    at newFn (xxx\client\node_modules\@babel\traverse\lib\visitors.js:179:21)
    at NodePath._call (xxx\client\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (xxx\client\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (xxx\client\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (xxx\client\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (xxx\client\node_modules\@babel\traverse\lib\context.js:84:19)
    at TraversalContext.visit (xxx\client\node_modules\@babel\traverse\lib\context.js:140:19)
```

**Desktop (please complete the following information):**

- OS: [e.g. iOS] *
- Browser [e.g. chrome, safari] *
- Version [e.g. 22] `7.5.3`

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] *
- OS: [e.g. iOS8.1] *
- Browser [e.g. stock browser, safari] *
- Version [e.g. 22] `7.5.3`

**Additional context**
As I understand it, the babel plugin tries to figure out which object `formatMessage` is extracted from, which isn't possible when destructuring directly from a function parameter.
Related PR: https://github.com/formatjs/formatjs-old/pull/582
Crashes here: https://github.com/formatjs/formatjs/blob/776390e/packages/babel-plugin-react-intl/src/index.ts#L281

**Comment by longlho** [comment]
@nstepien I can't seem to repro it w/ the test added

**Comment by nstepien** [comment]
Ah, turns out there is more to it: the `formatMessage` has to be in a block for the crash to occur.
The following should crash:
```js
function test({ formatMessage }) {
  if (true) {
    return formatMessage({ id: 'id', defaultMessage: 'msg' });
  }
}
```
```js
function test({ formatMessage }) {
  switch ('') {
    default:
      return formatMessage({ id: 'id', defaultMessage: 'msg' });
  }
}
```

Hint: a brace-less `if` won't crash.
```js
function test({ formatMessage }) {
  if (true) return formatMessage({ id: 'id', defaultMessage: 'msg' });
}
```

I don't know why destructuring outside the function parameters fixes it.

**Comment by longlho** [comment]
Thanks I'll take a look. Have you tried w/ the latest version?

**Comment by nstepien** [comment]
Just tried with `babel-plugin-react-intl@7.5.6` and it's fixed, thanks! Sorry for the bother.

**Comment by longlho** [comment]
Glad it works! Thanks for reporting!
