### ISSUE TITLE
Examples doesn't run locally

### ISSUE THREAD

**Issue by chyipin** [formatjs/formatjs#1746]
**Which package?**
`react-intl`

**Describe the bug**
The react-intl example failed to start

```
clim@LMTC-CLIM gh/formatjs (master=) (130) % lerna run example
info cli using local version of lerna
lerna notice cli v3.20.2
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run example"
react-intl: yarn run v1.22.4
react-intl: $ parcel examples/index.html
react-intl: Server running at http://localhost:1234 
react-intl: 🚨  /Users/clim/Projects/gh/formatjs/packages/react-intl/examples/index.tsx:13:8: Cannot resolve dependency 'core-js/stable'
react-intl:     at Resolver.resolve (/Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Resolver.js:71:17)
react-intl:     at async Bundler.resolveAsset (/Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Bundler.js:433:18)
react-intl:     at async Bundler.resolveDep (/Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Bundler.js:484:14)
react-intl:     at async /Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Bundler.js:608:26
react-intl:     at async Promise.all (index 2)
react-intl:     at async Bundler.loadAsset (/Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Bundler.js:599:21)
react-intl:     at async /Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Bundler.js:610:13
react-intl:     at async Promise.all (index 0)
react-intl:     at async Bundler.loadAsset (/Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Bundler.js:599:21)
react-intl:     at async Bundler.processAsset (/Users/clim/Projects/gh/formatjs/node_modules/parcel/src/Bundler.js:557:5)
```

**To Reproduce**
1. Follow instructions to setup locally
```
> lerna bootstrap
> yarn build
```
2. Launch example
```
lerna run example
```

**Expected behavior**
The examples run at http://localhost:1234 

**Workaround**
I comment out the import and it runs fine…
```
// import 'core-js/stable';
```

**Comment by pyrocat101** [comment]
Posting here for posterity: let's add core-js as a dev dependency of react-intl
