### ISSUE TITLE
CLI compile-folder exception when data is invalid

### ISSUE THREAD

**Issue by lucasff** [formatjs/formatjs#2029]
In `@formatjs/cli` if any of the source JSON used to be processed by the `compile-folder` command, this exception is thrown:

```
TypeError: Cannot read property 'charCodeAt' of undefined
    at peg$parseselfClosingTag (node_modules/@formatjs/cli/node_modules/intl-messageformat-parser/src/parser.js:722:19)
    at peg$parsetagElement (node_modules/@formatjs/cli/node_modules/intl-messageformat-parser/src/parser.js:681:14)
    at peg$parsemessageElement (node_modules/@formatjs/cli/node_modules/intl-messageformat-parser/src/parser.js:453:18)
    at peg$parsemessage (node_modules/@formatjs/cli/node_modules/intl-messageformat-parser/src/parser.js:434:14)
    at peg$parsestart (node_modules/@formatjs/cli/node_modules/intl-messageformat-parser/src/parser.js:428:14)
    at Object.peg$parse [as pegParse] (node_modules/@formatjs/cli/node_modules/intl-messageformat-parser/src/parser.js:3124:18)
    at Object.parse (node_modules/@formatjs/cli/node_modules/intl-messageformat-parser/index.js:31:24)
    at Object.<anonymous> (node_modules/@formatjs/cli/src/compile.js:97:62)
    at step (node_modules/@formatjs/cli/src/compile.js:33:23)
    at Object.next (node_modules/@formatjs/cli/src/compile.js:14:53)
```

**Expected behavior**
I'd expect the error to be nicer, maybe informing the file and/or key that fails?

**Comment by longlho** [comment]
Yup thanks a lot for reporting we'll take a look

**Comment by longlho** [comment]
@pyrocat101 can you help?

**Comment by milan-bc** [comment]
I upgraded to the latest version, but I still see this type of error message. I'm not sure what is wrong with my translation.
