### ISSUE TITLE
[babel-plugin-react-intl] options has an unknown property 'workspaceRoot'.

### ISSUE THREAD

**Issue by Yserz** [formatjs/formatjs#2121]
**Which package?**
babel-plugin-react-intl

**Describe the bug**

When updating the library Babel fails with the following error:

```
Invalid options object. babel-plugin-react-intl has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'workspaceRoot'. These properties are valid:
   object { moduleSourceName?, overrideIdFn?, idInterpolationPattern?, removeDefaultMessage?, additionalComponentNames?, pragma?, extractFromFormatMessageCall?, extractSourceLocation?, ast? } (While processing: ".../node_modules/babel-plugin-react-intl/index.js")
    at Object.validate [as default] (.../node_modules/schema-utils/dist/validate.js:98:11)
    at .../node_modules/babel-plugin-react-intl/index.js:225:27
    at .../node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at .../node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (.../node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (.../node_modules/gensync/index.js:254:32)
    at evaluateAsync (.../node_modules/gensync/index.js:284:5)
    at Function.errback (.../node_modules/gensync/index.js:108:7)
    at errback (.../node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
    at async (.../node_modules/gensync/index.js:183:31)
    at onFirstPause (.../node_modules/gensync/index.js:209:13)
    at Generator.next (<anonymous>)
    at cachedFunction (.../node_modules/@babel/core/lib/config/caching.js:68:46)
    at cachedFunction.next (<anonymous>)
 @ multi webpack-hot-middleware/client ../app/static/src/script/main.tsx script[1]
ℹ ｢wdm｣: Failed to compile.
```

babel.config.js
```
...
  plugins: [
    '@babel/plugin-proposal-class-properties',
    [
      'babel-plugin-react-intl',
      {
        messagesDir: translationsFolder,
      },
    ],
  ],
...
```

webpack.config.js
```
module: {
    rules: [
      {
        exclude: [/node_modules/],
        test: /\.[tj]sx?$/,
        use: [
          {
            loader: `babel-loader`,
          },
        ],
      },
	...
	]
...
}
```

package.json:
```
...
"babel-plugin-react-intl": "8.2.3",
"react-intl": "5.8.2",
"intl": "1.2.5",
"@babel/core": "7.11.6",
...
```

There's no `workspaceRoot` passed manually to the plugin. Do I miss any migration step?

**To Reproduce**

1. Update `babel-plugin-react-intl` from `7.9.4` to `8.2.3`
1. Build the project

**Expected behavior**
Update should not result in an error

**Comment by longlho** [comment]
https://github.com/formatjs/formatjs/blob/main/packages/babel-plugin-react-intl/CHANGELOG.md might provide some details

**Comment by Yserz** [comment]
Alright, thx for the pointer.

![image](https://user-images.githubusercontent.com/1138344/94200410-aa22c900-feba-11ea-83df-c447b91ec8d0.png)

Successfully migrated to `@formatjs/cli` :)

**Comment by macagua** [comment]
For me works, just set the version to ``babel-plugin-react-intl@7.9.4``, executing el following command at project root directory:
```
yarn add --dev babel-plugin-react-intl@7.9.4
```
