### ISSUE TITLE
[babel-plugin] removeDefaultMessage incompatible w/ idInterpolationPattern

### ISSUE THREAD

**Issue by IcanDivideBy0** [formatjs/formatjs#2305]
**Which package?**
`babel-plugin-react-intl`

**Describe the bug**
When using removeDefaultMessage, babel compilation crashes:
```
SyntaxError: xxx.js: NodePath has been removed so is read-only.
    at File.buildCodeFrameError (xxx/node_modules/@babel/core/lib/transformation/file/file.js:250:12)
    at NodePath.buildCodeFrameError (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/index.js:163:21)
    at NodePath._assertUnremoved (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:68:16)
    at NodePath.insertBefore (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/modification.js:32:8)
    at PluginPass.JSXOpeningElement (xxx/node_modules/babel-plugin-react-intl/index.js:331:52)
    at newFn (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (xxx/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:116:16) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```
I suspect that `defaultMessageAttr` is removed from AST [here](https://github.com/formatjs/formatjs/blob/main/packages/babel-plugin-react-intl/index.ts#L540), then possibly used [here](https://github.com/formatjs/formatjs/blob/main/packages/babel-plugin-react-intl/index.ts#L561-L572)

**To Reproduce**

1. use the following babel config:
```
{
  "plugins": [
    [
      "react-intl",
      {
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "removeDefaultMessage": true
      }
    ],
  ]
}
```

2. define some message ~w/ an id~:
**[edit]**: without an id

```
const messages = defineMessages({
  foo: {
    defaultMessage: "hello",
  },
});
```

**Expected behavior**
babel should not crash

**Additional context**
`@babel/core@7.12.3`
`babel-plugin-react-intl@8.2.13`

**Comment by IcanDivideBy0** [comment]
The problem really seem to come from [this line](https://github.com/formatjs/formatjs/blob/main/packages/babel-plugin-react-intl/index.ts#L565)

`defaultMessageAttr` has been removed from the AST so we can't `.insertBefore` it !
