### ISSUE TITLE
Node v14 error when using Intl.Locale polyfill

### ISSUE THREAD

**Issue by olessavluk** [formatjs/formatjs#2423]
**Which package?**
`@formatjs/intl-getcanonicallocales` and `@formatjs/intl-locale`

**Describe the bug**
When I am running tests for the server rendered react app receive following error:
```
    RangeError: Malformed unicode_language_subtag

      at parseUnicodeLanguageId (node_modules/@formatjs/intl-getcanonicallocales/src/parser.js:57:15)
      at Object.parseUnicodeLocaleId (node_modules/@formatjs/intl-getcanonicallocales/src/parser.js:240:16)  
      at applyUnicodeExtensionToTag (node_modules/@formatjs/intl-locale/index.js:42:42)
      at new Locale (node_modules/@formatjs/intl-locale/index.js:255:17)
      at Object.shouldPolyfill (node_modules/@formatjs/intl-locale/should-polyfill.js:8:9)
      at Object.<anonymous> (node_modules/@formatjs/intl-locale/polyfill.js:5:23)
```
I wasn't able to locate the problem and create minimal reproducible example. However when I :
 - add `import '@formatjs/intl-getcanonicallocales/polyfill';` error is gone
 - remove `import '@formatjs/intl-locale/polyfill'` error is gone
 
Could this mean that one of this polyfills is incompatible with Node?

**Additional context**
 - Node v14.15.3
 - Yarn 1.22.10

 <details>
<summary>package versions from `yarn.lock`</summary> 

```
"@jest/core@26.6.3"
"@formatjs/ecma402-abstract@1.5.0":
"@formatjs/intl-datetimeformat@3.2.1":
    "@formatjs/ecma402-abstract" "1.5.0"
"@formatjs/intl-displaynames@4.0.2":
    "@formatjs/ecma402-abstract" "1.5.0"
"@formatjs/intl-getcanonicallocales@1.5.3":
"@formatjs/intl-listformat@5.0.2":
    "@formatjs/ecma402-abstract" "1.5.0"
"@formatjs/intl-locale@2.4.10":
    "@formatjs/ecma402-abstract" "1.5.0"
    "@formatjs/intl-getcanonicallocales" "1.5.3"
"@formatjs/intl-numberformat@6.1.1":
    "@formatjs/ecma402-abstract" "1.5.0"
"@formatjs/intl-pluralrules@4.0.1":
    "@formatjs/ecma402-abstract" "1.5.0"
"@formatjs/intl-relativetimeformat@8.0.1":
    "@formatjs/ecma402-abstract" "1.5.0"
"@formatjs/intl@1.4.13":
    "@formatjs/ecma402-abstract" "1.5.0"
    "@formatjs/intl-datetimeformat" "3.2.1"
    "@formatjs/intl-displaynames" "4.0.2"
    "@formatjs/intl-listformat" "5.0.2"
    "@formatjs/intl-relativetimeformat" "8.0.1"
    "@formatjs/ecma402-abstract" "1.5.0"
    "@formatjs/ecma402-abstract" "1.5.0"
    "@formatjs/intl" "1.4.13"
    "@formatjs/intl-displaynames" "4.0.2"
    "@formatjs/intl-listformat" "5.0.2"
    "@formatjs/intl-relativetimeformat" "8.0.1"
 ```
</details>

**Comment by longlho** [comment]
Node v14 shouldn't need those polyfills.

**Comment by olessavluk** [comment]
@longlho but also shouldn't crash if one (but not all) of this polyfills included, right?

(I use them for Safari, it's just that same code executed on server too)

**Comment by longlho** [comment]
Yup we'll take a look at the bug

**Comment by longlho** [comment]
@olessavluk for your case u should add `@formatjs/intl-getcanonicallocales/polyfill` bc of https://bugs.chromium.org/p/v8/issues/detail?id=10682 (it's a chromium bug but it's actually a ICU bug which all browsers use)
