### ISSUE TITLE
Tag attributes cause the MessageFormat parser to fail

### ISSUE THREAD

**Issue by nwhittaker** [formatjs/formatjs#2682]
## Which package?
`intl-messageformat-parser`

## Describe the bug
The parser throws an error on the following string construction: `<a href="">link</a>`.

## To Reproduce

```js
test('tag with attribute', () => {
  expect(
    pegParse('<foo attribute>bar</foo>')
  ).toMatchSnapshot();
});
```

The above test fails with the following error:

```
Error [SyntaxError]: Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.
    at peg$buildStructuredError (.../intl-messageformat-parser/src/parser.js:401:16)
    at Object.peg$parse [as pegParse] (.../intl-messageformat-parser/src/parser.js:3109:15)
    at parse (.../intl-messageformat-parser/index.js:11:24)
   ... {
  expected: [
    { type: 'other', description: 'double apostrophes' },
    { type: 'literal', text: "'", ignoreCase: false },
    { type: 'literal', text: '\n', ignoreCase: false },
    { type: 'other', description: 'tagElement' },
    { type: 'other', description: 'double apostrophes' },
    { type: 'literal', text: "'", ignoreCase: false },
    { type: 'literal', text: '\n', ignoreCase: false },
    { type: 'other', description: 'argumentElement' },
    { type: 'literal', text: '{', ignoreCase: false },
    { type: 'literal', text: '{', ignoreCase: false },
    { type: 'literal', text: '{', ignoreCase: false },
    { type: 'literal', text: '{', ignoreCase: false },
    { type: 'literal', text: '#', ignoreCase: false },
    { type: 'end' }
  ],
  found: '<',
  location: {
    start: { offset: 18, line: 1, column: 19 },
    end: { offset: 19, line: 1, column: 20 }
  }
}
```

## Expected behavior
No error is thrown.

## Desktop (please complete the following information):

- OS: macOS v11.2.3
- Browser: Node v14.15.4

**Comment by longlho** [comment]
u can pass in `ignoreTag` option to get the old behavior

**Comment by nwhittaker** [comment]
>u can pass in ignoreTag option to get the old behavior

Thanks @longlho, that works for me. I didn't realize the `IntlMessageFormat` options also applied to the `Intl MessageFormat Parser`.

**Comment by longlho** [comment]
If you wanna PR to update the doc that'd be great too :)
