### ISSUE TITLE
Compiling messages fails with "Error validating message "undefined" with ID "0323d" in file"

### ISSUE THREAD

**Issue by TimDaub** [formatjs/formatjs#2700]
I have successfully extracted raw messages from my code base using `@formatjs/cli`. Here's `en-US/messages.json`:

```json
{
  "0323d": {
    "defaultMessage": "Logout"
  }
}
```

Then I try compiling my messages such that I can use them in the code:

```bash
formatjs compile src/js/locales/raw/en-US/messages.json --format crowdin --out-file src/js/locales/compiled/en-US/messages.json --ast
```

I use `formatMessage` as described [here](https://github.com/formatjs/formatjs/issues/2694#issuecomment-796947707).

```js
import { createIntl, createIntlCache } from "@formatjs/intl";
const cache = createIntlCache();
import enUS from "./locales/compiled/en-US/messages.json";
const intl = createIntl({ locale: "en-US", messages: enUS }, cache);
intl.formatMessage(...)
```

But when I run `formatjs compile`, I get:

```bash
{ '0323d': undefined }
Error validating message "undefined" with ID "0323d" in file "src/js/locales/raw/en-US/messages.json"
TypeError: Cannot read property 'charCodeAt' of undefined
    at peg$parseselfClosingTag (/Users/user/Projects/project/node_modules/intl-messageformat-parser/src/parser.js:699:19)
    at peg$parsetagElement (/Users/user/Projects/project/node_modules/intl-messageformat-parser/src/parser.js:658:14)
    at peg$parsemessageElement (/Users/user/Projects/project/node_modules/intl-messageformat-parser/src/parser.js:430:18)
    at peg$parsemessage (/Users/user/Projects/project/node_modules/intl-messageformat-parser/src/parser.js:411:14)
    at peg$parsestart (/Users/user/Projects/project/node_modules/intl-messageformat-parser/src/parser.js:405:14)
    at Object.peg$parse [as pegParse] (/Users/user/Projects/project/node_modules/intl-messageformat-parser/src/parser.js:3101:18)
    at Object.parse (/Users/user/Projects/project/node_modules/intl-messageformat-parser/index.js:11:24)
    at /Users/user/Projects/project/node_modules/@formatjs/cli/src/compile.js:45:70
    at step (/Users/user/Projects/project/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/user/Projects/project/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:124:57)
```

**Comment by longlho** [comment]
u have to extract with `--format crowdin` as well. Basically the `extract` & `compile` formats have to be the same
