### ISSUE TITLE
Flakey cli dependency

### ISSUE THREAD

**Issue by asvny** [formatjs/formatjs#2723]
## Which package?
cli

## Describe the bug
In CI .. we frequently get `TypeError: fsStat.Settings is not a constructor` error.
Looks like this is because of `fast-glob` which format/cli depends on.

```
TypeError: fsStat.Settings is not a constructor
463    at new Reader (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/fast-glob/out/readers/reader.js:9:32)
464    at new ReaderSync (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/fast-glob/out/readers/sync.js:8:9)
465    at new ProviderSync (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/fast-glob/out/providers/sync.js:8:24)
466    at getWorks (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/fast-glob/out/index.js:57:22)
467    at AsyncFunction.sync (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/fast-glob/out/index.js:19:23)
468    at Object.<anonymous> (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/@formatjs/cli/src/cli.js:54:87)
469    at step (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:143:27)
470    at Object.next (/builds/catapult-sports/catapult-platform/catapult-platform/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:124:57)
471    at /builds/catapult-sports/catapult-platform/catapult-platform/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:117:75
```
## Expected behavior
Should work always without flakiness.

**Comment by longlho** [comment]
What node version are you running?

**Comment by asvny** [comment]
I reckon it is `12.18.1`  ... wondering if you have come across this before ? For context out of 10 pipelines atleast 4-6 fail inititally then on retry it passes.

```
"intl:extract": "formatjs extract 'src/**/*.ts*' --out-file 'src/lang/en.json' --format simple --id-interpolation-pattern '[sha512:contenthash:base64:6]'",
"intl:compile": "formatjs compile --format simple --ast '../../**/lang/en.json' --out-file 'src/compiled-lang/en.json'",
"intl:compile:folder": "formatjs compile-folder --format simple --ast src/lang src/compiled-lang",
"intl:compile:pseudo": "formatjs compile --format simple --ast --pseudo-locale en-XB '../../**/lang/en.json' --out-file 'src/compiled-lang/en-XB.json'",        
"intl:build": "yarn intl:extract && yarn intl:compile:folder && yarn intl:compile && yarn intl:compile:pseudo"  
```

Long way to go ... but just getting started. We run `intl:build` to generate the files.

Did some digging .. looks like it is because of `@nodelib/fs.stat` dep which `fast-glob` uses.
https://github.com/nodelib/nodelib/blob/master/packages/fs/fs.stat/src/index.ts#L40

**Comment by longlho** [comment]
hmm I haven't seen this before but if it's flaky there's something wrong with the pipeline setup itself.

**Comment by asvny** [comment]
Just curious ... what version you use for node and npm or yarn ?

**Comment by longlho** [comment]
I use Node 14 bc Node 12 doesn't have full ICU

**Comment by asvny** [comment]
Closing this .. since we don't see this happening for a while .. thank you.
