### ISSUE TITLE
eslint-plugin-formatjs doesn’t work with yarn pnp

### ISSUE THREAD

**Issue by lensbart** [formatjs/formatjs#2756]
Hello!

Not sure what’s causing the issue, I just see from the output dialog window that there was an error loading the plugin:

```
[Info  - 7:18:31 PM] ESLint server is starting
[Info  - 7:18:31 PM] ESLint server running in node v12.18.3
[Info  - 7:18:31 PM] ESLint server is running.
[Info  - 7:18:31 PM] ESLint library loaded from: codebase/.yarn/sdks/eslint/lib/api.js
(node:81914) UnhandledPromiseRejectionWarning: Error: Failed to load config "formatjs" to extend from.
Referenced from: codebase/.eslintrc.json
    at configInvalidError (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
```

Other plugins are working fine and my editor is correctly configured for Yarn PnP as per [their instructions](https://next.yarnpkg.com/getting-started/editor-sdks#vscode).

**Comment by longlho** [comment]
I have never used whatever yarn pnp is so unfortunately idk what's going on.

**Comment by lensbart** [comment]
It’s a relatively new module resolution method in Yarn 2 ([here](https://next.yarnpkg.com/features/pnp) you can find some more information, if interested).

It comes with somewhat stricter rules, e.g. that any dependency that is used by a module should be declared in its `package.json` file.

I’m not sure that this is causing the plugin to fail because the error message I get doesn’t contain much detail. But I can see that the following imports are missing in the dependencies list:

* `estree` (used in https://github.com/formatjs/formatjs/blob/main/packages/eslint-plugin-formatjs/rules/blacklist-elements.ts)
* `@formatjs/icu-messageformat-parser` (used in https://github.com/formatjs/formatjs/blob/main/packages/eslint-plugin-formatjs/rules/blacklist-elements.ts)
* `json-schema` (used in https://github.com/formatjs/formatjs/blob/main/packages/eslint-plugin-formatjs/rules/enforce-plural-rules.ts)

**Comment by longlho** [comment]
those are type dependencies but not runtime deps

**Comment by longlho** [comment]
can u give latest version a try? maybe that fixes it

**Comment by lensbart** [comment]
Just tried again for `eslint-plugin-formatjs@2.14.5` and ran into the same issue:

```
(node:1235) UnhandledPromiseRejectionWarning: Error: Failed to load config "formatjs" to extend from.
Referenced from: [...]/.eslintrc.json
    at configInvalidError ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile ([...]/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18)
(node:1235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1235) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by longlho** [comment]
yeah I have no idea then since I don't use `yarn pnp`
