### ISSUE TITLE
ts-transformer: error occurs if "{value, number}" is used when ast option enabled

### ISSUE THREAD

**Issue by mabeyj** [formatjs/formatjs#2993]
## Which package?
@formatjs/ts-transformer

## Describe the bug
When using ts-transformer with ts-loader and `{ast: true}`, an error occurs when using a `{value, number}` argument in messages. Specifically, when the optional format element (like `{value, number, ::percent}`) is not defined.

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at objToTSNode (/sandbox/node_modules/@formatjs/ts-transformer/src/transform.js:34:24)
    at /sandbox/node_modules/@formatjs/ts-transformer/src/transform.js:40:23
    at Array.map (<anonymous>)
    at objToTSNode (/sandbox/node_modules/@formatjs/ts-transformer/src/transform.js:34:37)
    at /sandbox/node_modules/@formatjs/ts-transformer/src/transform.js:46:80
    at Array.map (<anonymous>)
    at messageASTToTSNode (/sandbox/node_modules/@formatjs/ts-transformer/src/transform.js:46:53)
    at generateNewProperties (/sandbox/node_modules/@formatjs/ts-transformer/src/transform.js:305:58)
    at extractMessageFromJsxComponent (/sandbox/node_modules/@formatjs/ts-transformer/src/transform.js:265:20)
```

### Codesandbox URL

https://codesandbox.io/s/ts-transformer-ts-loader-value-number-ast-error-7spxg

### Reproducible Steps/Repo

Open a terminal in CodeSandbox, then run `yarn build` to see the above error.

## Expected behavior
There should be no error in this case.

## Additional context
An error doesn't occur if the `ast` option is disabled. Not sure if this issue occurs with other build tools.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.
