### ISSUE TITLE
formatjs/cli extract not using ignore option

### ISSUE THREAD

**Issue by andeliv** [formatjs/formatjs#3027]
## Which package?
@formatjs/cli

## Describe the bug
Running extract command 
`npx @formatjs/cli extract --throws '../**/src/**/*.{ts,tsx}' --ignore '../**/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'`
 throws an error
```
Error: Error processing file ../web-main/packages/web/src/@types/logger.d.ts 
Debug Failure. Output generation failed
    at Object.transpileModule (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/typescript/lib/typescript.js:135663:29)
    at /Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/src/parse_script.js:16:43
    at processFile (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/src/extract.js:55:9)
    at /Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/src/extract.js:96:59
    at step (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:114:62)
```
It started failing ~4 days ago, before that `--ignore` seemed to work fine.

### Reproducible Steps/Repo
https://github.com/andeliv/formatjs-cli-error

1) cd packages/trn
2) yarn intl:extract-all
3) see the error `Error: Error processing file ../web-main/packages/web/src/@types/logger.d.ts`

After removal of the `logger.d.ts` file all messages from both packages are extracted correctly

## Expected behavior
Strings are extracted from all packages and files from `--ignore` option are ignored

**Comment by chenrui333** [comment]
Second to this, this broke our pipeline most recently and we could not figure out the root cause.

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by chenrui333** [comment]
@longlho thank you, that would be awesome.

**Comment by longlho** [comment]
ok this is an issue upstream with `fast-glob` https://github.com/mrmlnc/fast-glob/issues/325 so for now you can pin `fast-glob` to `3.2.5`

**Comment by chenrui333** [comment]
NICE!! Let me give that a try.

**Comment by chenrui333** [comment]
Just gave a try, after pinning `fast-glob` version, I still could not get it working for me.

```
$ yarn intl:extract-all
yarn run v1.22.10
$ npm i fast-glob@3.2.5 && npx @formatjs/cli extract --throws '../**/src/**/*.{ts,tsx}' --ignore '../**/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN trn@1.0.0 No description
npm WARN trn@1.0.0 No repository field.

+ fast-glob@3.2.5
added 18 packages from 25 contributors and audited 18 packages in 3.248s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npx: installed 90 in 5.868s
Error: Error processing file ../web-main/packages/web/src/@types/logger.d.ts
```

**Comment by longlho** [comment]
Try installing @formatjs/cli as well as npx might be resolving dep differently

**Comment by chenrui333** [comment]
Yes, it works

```
   "scripts": {
-    "intl:extract-all": "npx @formatjs/cli extract --throws '../**/src/**/*.{ts,tsx}' --ignore '../**/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'",
+    "intl:extract-all": "formatjs extract --throws '../**/src/**/*.{ts,tsx}' --ignore '../**/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'",
     "intl:extract-components": "npx @formatjs/cli extract --throws '../web-components/src/**/*.{ts,tsx}' --ignore '../web-components/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'",
     "intl:extract-main": "npx @formatjs/cli extract --throws '../web-main/packages/web/src/**/*.{ts,tsx}' --ignore '../web-main/packages/web/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'"
   },
-  "dependencies": {}
+  "dependencies": {
+    "@formatjs/cli": "4.2.25",
+    "fast-glob": "3.2.5"
+  }
```

```
$ yarn intl:extract-all
yarn run v1.22.10
$ formatjs extract --throws '../**/src/**/*.{ts,tsx}' --ignore '../**/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'
✨  Done in 0.87s.
```

**Comment by chenrui333** [comment]
If I used `npm install` and then `yarn intl:extract-all` it works fine, but if I switch to `yarn` and then `yarn intl:extract-all`, it does not quite work as expected.

I think this might be more related to `yarn workspace` 🤔

**Comment by longlho** [comment]
yeah `yarn` dep resolution is weird. I'm closing this since this is an issue upstream so feel free to follow that GH issue.
