### ISSUE TITLE
formatjs compile-folder not work

### ISSUE THREAD

**Issue by hongdeyuan** [formatjs/formatjs#3094]
## Which package?
"@formatjs/cli": "^4.2.29",

## Describe the bug
I am @formatjs/cli compiled Chinese sentences to english with parameters, and an error occurred：

yarn commend:  `formatjs compile-folder --ast --format simple lang/locales lang/compiled-locales`

```
[@formatjs/cli] [WARN] Error validating message "This is vm{query.id}page." with ID "这是第{id}虚拟机页。" in file "lang/locales/enUS.json"
SyntaxError: MALFORMED_ARGUMENT
    at Object.parse (/Users/xsky/Documents/project/pluto/node_modules/@formatjs/icu-messageformat-parser/index.js:34:21)
    at Object.<anonymous> (/Users/xsky/Documents/project/pluto/node_modules/@formatjs/cli/src/compile.js:48:69)
    at step (/Users/xsky/Documents/project/pluto/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/xsky/Documents/project/pluto/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/xsky/Documents/project/pluto/node_modules/tslib/tslib.js:114:62)
```
```
{
    "这是第{id}虚拟机页。": "This is vm {query.id} page."
}
```

### Codesandbox URL

none

### Reproducible Steps/Repo

1. "extract:i18n": "formatjs extract '{pages,components}/**/*.{js,ts,tsx}' --format simple --additional-function-names 't' --id-interpolation-pattern '[sha512:contenthash:base64:6]' --out-file lang/locales/enUS.json",

2.  "compile:i18n": "formatjs compile-folder --ast --format simple lang/locales lang/compiled-locales",
3. yarn extract:i18n
4. yarn compile:i18n

## Expected behavior
- Is it true that English sentences are not supported '{}'

## Screenshots
![image](https://user-images.githubusercontent.com/37143703/128176273-953a4682-3d83-4019-8276-a2a437fd5693.png)

## Desktop (please complete the following information):

- OS: 11.0 Beta版(20A4300b)
- Browser : chrome
- Version : "@formatjs/cli": "^4.2.29",

**Comment by hongdeyuan** [comment]
When I remove {} it works fine：
![image](https://user-images.githubusercontent.com/37143703/128177720-2656d461-6851-48b1-aaf6-ec9774e8480a.png)
