### ISSUE TITLE
Keep getting typeError: Cannot read property 'createJsxAttribute' of undefined when use ts-transformer

### ISSUE THREAD

**Issue by haoranliu1220** [formatjs/formatjs#3116]
## Which package?
'@formatjs/ts-transformer/ts-jest-integration'

## Describe the bug
I am trying to set up the ts-transformer in the jest.config.js to auto inject the id to the formattedmessage, but I keep getthing this issue :

 Test suite failed to run

    TypeError: Cannot read property 'createJsxAttribute' of undefined

      at generateNewProperties (node_modules/@formatjs/ts-transformer/src/transform.js:310:17)
      at extractMessageFromJsxComponent (node_modules/@formatjs/ts-transformer/src/transform.js:274:20)
      at visitor (node_modules/@formatjs/ts-transformer/src/transform.js:407:19)
      at visitNodes (node_modules/typescript/lib/typescript.js:74849:48)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:75211:115)
      at visitor (node_modules/@formatjs/ts-transformer/src/transform.js:409:19)
      at visitNodes (node_modules/typescript/lib/typescript.js:74849:48)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:75211:115)
      at visitor (node_modules/@formatjs/ts-transformer/src/transform.js:409:19)
      at visitNodes (node_modules/typescript/lib/typescript.js:74849:48)

## To Reproduce
My jest config is:

```
module.exports = {
  // Automatically clear mock calls and instances between every test
  clearMocks: true,
  // An array of glob patterns indicating a set of files for which coverage information should be collected
  collectCoverageFrom: ['src/**/*.ts(x)'],
  // The directory where Jest should output its coverage files
  coverageDirectory: 'coverage',
  // An array of regexp pattern strings used to skip coverage collection
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/config/',
    '/types.ts$/',
    '/*.d.ts$/',
    '/constants?.ts$/',
    '/tests/',
    '/types/',
    '/lib/',
  ],
  // An object that configures minimum threshold enforcement for coverage results
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
  },
  // An array of file extensions your modules use
  moduleFileExtensions: ['js', 'json', 'ts', 'tsx', 'node'],
  // The glob patterns Jest uses to detect test files
  testMatch: ['**/?*.spec.[tj]s?(x)'],

  // An array of regexp pattern strings that are matched against all test paths, matched tests are skipped
  testPathIgnorePatterns: ['/node_modules/'],
  // A map from regular expressions to paths to transformers
  transform: {
    '.(js|tsx|ts?)$': 'ts-jest',
  },
  globals: {
    'ts-jest': {
      tsConfig: 'tsconfig.test.json',
      astTransformers: {
        before: [
          {
            path: '@formatjs/ts-transformer/ts-jest-integration',
            options: {
              overrideIdFn: '[sha512:contenthash:base64:6]',
            },
          },
        ],
      },
    },
  },

  // An array of directory names to be searched recursively up from the requiring module's location
  moduleDirectories: ['node_modules', 'src'],

  setupFilesAfterEnv: ['<rootDir>/tests/jestSetUp.ts'],
```

my tsconfig.test.json is
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "allowJs": true
  },
  "include": ["**/*.spec.tsx", "**/*.spec.ts"]
}
```

my tsconfig.json is

```
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["esnext", "dom"],
    "listFiles": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "preserveConstEnums": true,
    "removeComments": true,
    "skipLibCheck": true,
    "target": "ES5",
    "noImplicitThis": true
  },
  "include": ["./src/**/*", "./tests/**/*"],
  "exclude": ["node_modules", "lib", "coverage"]
}
```

my jestSetUp.ts is

```
import '@testing-library/jest-dom';
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```

### Codesandbox URL

Please include a codesandbox URL if possible

**Comment by longlho** [comment]
Do you have a repro repo?
