### ISSUE TITLE
Missing locale data for *blank*

### ISSUE THREAD

**Issue by MoSattler** [formatjs/formatjs#3300]
## Which package?
@formatjs/intl-relativetimeformat

## Describe the bug

Every time I try to use <FormattedRelativeTime /> I get the following error. I am using the latest expo version of react-native.

```
mobile_1    | [23:19:20] [@formatjs/intl Error FORMAT_ERROR] Error formatting relative time. 
mobile_1    | Locale: en
mobile_1    |  
mobile_1    | 
mobile_1    | Missing locale data for 
mobile_1    | invariant@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:285171:20
mobile_1    | ResolveLocale@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:285056:24
mobile_1    | InitializeRelativeTimeFormat@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:336864:52
mobile_1    | RelativeTimeFormat@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:336702:78
mobile_1    | RelativeTimeFormat@[native code]
mobile_1    | http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:285935:122
mobile_1    | variadic@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:288059:31
mobile_1    | variadic@[native code]
mobile_1    | formatRelativeTime@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:289006:26
mobile_1    | formatRelativeTime@[native code]
mobile_1    | SimpleFormattedRelativeTime@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:289378:51
mobile_1    | renderWithHooks@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:16735:33
mobile_1    | updateFunctionComponent@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:18743:41
mobile_1    | beginWork$1@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:23743:29
mobile_1    | performUnitOfWork@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:22821:29
mobile_1    | workLoopSync@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:22766:28
mobile_1    | renderRootSync@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:22739:25
mobile_1    | performSyncWorkOnRoot@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:22501:38
mobile_1    | performSyncWorkOnRoot@[native code]
mobile_1    | http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13775:40
mobile_1    | unstable_runWithPriority@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:56909:30
mobile_1    | flushSyncCallbackQueueImpl@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13770:30
mobile_1    | flushSyncCallbackQueue@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13759:35
mobile_1    | scheduleUpdateOnFiber@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:22220:37
mobile_1    | dispatchAction@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:17650:32
mobile_1    | dispatchAction@[native code]
mobile_1    | _callTimer@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:32404:17
mobile_1    | callTimers@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:32612:19
mobile_1    | __callFunction@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3749:36
mobile_1    | http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3477:31
mobile_1    | __guard@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3703:15
mobile_1    | callFunctionReturnFlushedQueue@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3476:21
mobile_1    | callFunctionReturnFlushedQueue@[native code]
mobile_1    | at node_modules/@formatjs/intl/src/error.js:23:8 in IntlError
mobile_1    | at node_modules/@formatjs/intl/src/error.js:62:5 in <anonymous>
mobile_1    | at node_modules/@formatjs/intl/src/relativeTime.js:30:5 in formatRelativeTime
mobile_1    | at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:289378:50 in SimpleFormattedRelativeTime


```

### Codesandbox URL

[Please include a codesandbox URL if possible](https://snack.expo.dev/658zgmnLN)

## Screenshots
![Simulator Screen Shot - iPhone 8 - 2021-12-13 at 00 18 10](https://user-images.githubusercontent.com/64152453/145733677-49ae81d7-2410-43e8-8812-c6804ba22b89.png)

## Desktop (please complete the following information):

iOS

## Smartphone (please complete the following information):

- Device: iPhone Simulator
- OS: iOS13
- Browser Expo React Native

**Comment by longlho** [comment]
you need to add some locale-data to relativetimeformat polyfill just like you do w/ other polyfills
