### ISSUE TITLE
[swc-plugin] Method visitTsType not implemented

### ISSUE THREAD

**Issue by elado** [formatjs/formatjs#3690]
## Which package?
`@formatjs/swc-plugin`

## Describe the bug

Hitting this error when I have code with generics in .tsx files

```ts
export function f<TType>(x: TType): TType {
  return x;
}
```

```
Error: Method visitTsType not implemented.
    at FormatJSTransformer.visitTsType (<root>/node_modules/@swc/core/Visitor.js:1178:15)
    at FormatJSTransformer.visitTsTypeAliasDeclaration (<root>/node_modules/@swc/core/Visitor.js:413:33)
    at FormatJSTransformer.visitDeclaration (<root>/node_modules/@swc/core/Visitor.js:394:29)
    at FormatJSTransformer.visitExportDeclaration (<root>/node_modules/@swc/core/Visitor.js:164:30)
    at FormatJSTransformer.visitModuleDeclaration (<root>/node_modules/@swc/core/Visitor.js:43:29)
    at FormatJSTransformer.visitModuleItem (<root>/node_modules/@swc/core/Visitor.js:35:29)
    at Array.map (<anonymous>)
    at FormatJSTransformer.visitModuleItems (<root>/node_modules/@swc/core/Visitor.js:22:22)
    at FormatJSTransformer.visitModule (<root>/node_modules/@swc/core/Visitor.js:14:23)
    at FormatJSTransformer.visitProgram (<root>/node_modules/@swc/core/Visitor.js:8:29) {
```

The actual node it fails on is the generic:
```js
{
  type: 'TsTypeReference',
  span: { start: 153, end: 158, ctxt: 0 },
  typeName: {
    type: 'Identifier',
    span: { start: 153, end: 158, ctxt: 0 },
    value: 'TType',
    optional: false
  },
  typeParams: null
}
```

## To Reproduce

Rollup SWC plugin config:

```js
swc({
  jsc: {
    parser: {
      syntax: 'typescript',
      tsx: true,
    },
    target: 'es2018',
  },
  plugin: (m: any) =>
    new FormatJSTransformer({
      overrideIdFn: '[sha512:contenthash:base64:6]',
      ast: true,
      removeDefaultMessage: false,
    }).visitProgram(m),
})
```

## Desktop (please complete the following information):

- OS: macOS
- `@formatjs/swc-plugin@1.4.5`
- `@swc/core@1.2.206`

## More info

I added manually

```js
    FormatJSTransformer.prototype.visitTsType = function (node) {
      return node
    }
```

in `node_modules/@formatjs/swc-plugin/src/transform.js`.

That removes the error, but with a simple file with

```tsx
import React from 'react';
import { FormattedMessage } from 'react-intl';

export const Foo = () => <FormattedMessage defaultMessage="Foo" description="Foo" />;
```

I'm getting this with `RUST_BACKTRACE=full`:

```
thread '<unnamed>' panicked at 'failed to deserialize Program: Error("missing field `span`", line: 0, column: 0)', crates/binding_core_node/src/transform.rs:59:49
stack backtrace:
   0:        0x129b15b10 - _wasmer_vm_raise_trap
   1:        0x129b34b2c - _wasmer_vm_raise_trap
   2:        0x129b11778 - _wasmer_vm_raise_trap
   3:        0x129b172a8 - _wasmer_vm_raise_trap
   4:        0x129b17010 - _wasmer_vm_raise_trap
   5:        0x129b1773c - _wasmer_vm_raise_trap
   6:        0x129b17670 - _wasmer_vm_raise_trap
   7:        0x129b15fec - _wasmer_vm_raise_trap
   8:        0x129b173c8 - _wasmer_vm_raise_trap
   9:        0x129bdef78 - _wasmer_vm_raise_trap
  10:        0x129bdf01c - _wasmer_vm_raise_trap
  11:        0x1282a6f18 - <unknown>
  12:        0x1282a3ae0 - <unknown>
  13:        0x1281d33b8 - <unknown>
  14:        0x12829fd04 - <unknown>
  15:        0x1281686b0 - <unknown>
  16:        0x10321abd4 - _worker
  17:        0x1a766626c - __pthread_deallocate
[Error: failed to handle: failed to deserialize Program: Error("missing field `span`", line: 0, column: 0)

Stack backtrace:
   0: _wasmer_vm_raise_trap
   1: _wasmer_vm_raise_trap
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: _worker
   7: __pthread_deallocate] {
  code: 'PLUGIN_ERROR',
  pluginCode: 'GenericFailure',
  plugin: 'swc',
  hook: 'transform',
  id: '<foo>/index.tsx',
  watchFiles: [
    '<foo>/index.tsx',
  ]
}
```

It only happens when there's a `FormattedMessage` jsx.

**Comment by longlho** [comment]
do you have a codesandbox?

**Comment by elado** [comment]
I couldn't get it to work on a sandbox/stackblitz because of the native extension, but here's the code:

```js
import { transformSync } from "@swc/core";
import FormatJSTransformer from "@formatjs/swc-plugin";

const out = transformSync(
  `
  import { FormattedMessage } from "react-intl";

  export const Foo = () => (
    <div>
      <FormattedMessage defaultMessage="foo" description="bar" />
    </div>
  );`,
  {
    jsc: {
      parser: {
        syntax: "typescript",
        tsx: true,
      },
      target: "es2018",
    },
    plugin: (m) => {
      return new FormatJSTransformer.FormatJSTransformer({
        overrideIdFn: "[sha512:contenthash:base64:6]",
        ast: true,
        removeDefaultMessage: false,
      }).visitProgram(m);
    },
  }
);

console.log(out);
```

**Comment by elado** [comment]
Not stale

**Comment by longlho** [comment]
Can you make an example repo so i can just clone?

**Comment by elado** [comment]
@longlho https://github.com/elado/formatjs-swc-error
