### ISSUE TITLE
ts-transformer doesn't work with Jest

### ISSUE THREAD

**Issue by garvae** [formatjs/formatjs#3760]
## Which package?
@formatjs/ts-transformer/ts-jest-integration

## Describe the bug
Following [docs](https://formatjs.io/docs/tooling/ts-transformer/) I added additional config to my `jest.config.js`.
When I run my tests (.tsx files) I get an error:

```text
 ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'compilerModule')

      at Object.factory (node_modules/@formatjs/ts-transformer/ts-jest-integration.js:8:63)
      at node_modules/ts-jest/dist/config/config-set.js:270:61
          at Array.map (<anonymous>)
      at resolveTransformers (node_modules/ts-jest/dist/config/config-set.js:262:41)
      at ConfigSet._setupTsJestCfg (node_modules/ts-jest/dist/config/config-set.js:276:74)
      at new ConfigSet (node_modules/ts-jest/dist/config/config-set.js:158:14)
      at TsJestTransformer.configsFor (node_modules/ts-jest/dist/ts-jest-transformer.js:44:29)
      at TsJestTransformer.getCacheKey (node_modules/ts-jest/dist/ts-jest-transformer.js:106:28)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:256:23)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:290:27)
```

When I remove [this](https://formatjs.io/docs/tooling/ts-transformer/) additional config,
change my tests files to `.jsx` and run my tests with similar babel config - all works fine. (I will leave all my configs below)

<hr/>

This is what I added to `jest.config.js` config (and this is what cause an error):
```
{
  // ...
  globals: {
    // ...
    'ts-jest': {
      astTransformers: { before: [ {
        options: {
          ast: true,
          overrideIdFn: '[sha512:contenthash:base64:6]',
        },
        path: '@formatjs/ts-transformer/ts-jest-integration',
      } ] },
      // ...
    },
  },
  // ...
};
```

Full config `jest.config.js`:
```js
const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('./tsconfig');

const config = {
  bail: 1,
  cacheDirectory: './cache/jest',
  clearMocks: true,
  collectCoverage: false,
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!<rootDir>/node_modules/',
    '!<rootDir>/src/**/*.d.{js,jsx,ts,tsx}',
  ],
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: [ '/node_modules/' ],
  coverageProvider: 'v8',
  coverageReporters: [
    'json',
    'text',
    'lcov',
    'clover',
  ],
  errorOnDeprecated: true,
  globals: {
    '__DEV__': true,
    'ts-jest': {
      astTransformers: { before: [ {
        options: {
          ast: true,
          overrideIdFn: '[sha512:contenthash:base64:6]',
        },
        path: '@formatjs/ts-transformer/ts-jest-integration',
      } ] },
      tsconfig: './tsconfig.test.json',
    },
  },
  maxWorkers: '50%',
  moduleDirectories: [ 'node_modules', 'src' ],
  moduleFileExtensions: [
    'js',
    'mjs',
    'cjs',
    'jsx',
    'ts',
    'tsx',
    'json',
    'node',
  ],
  moduleNameMapper: {
    ...pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/src/' }),
    '^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
  },
  rootDir: './',
  roots: [ '<rootDir>/src' ],
  setupFilesAfterEnv: [ '<rootDir>/src/tests/config/setup-tests.ts' ],
  slowTestThreshold: 10,
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {},
  testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
  testPathIgnorePatterns: [ '\\\\node_modules\\\\' ],
  transform: {
    '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
    '^.+\\.(js|jsx)$': 'babel-jest',
    '^.+\\.(ts|tsx)?$': 'ts-jest',
    '^.+\\.svg$': '<rootDir>/src/tests/transformers/svg.js',
  },
  transformIgnorePatterns: [ 'node_modules/(?!(lodash-es|react-dnd|react-dnd-touch-backend|@react-dnd|use-debounce))' ],
  verbose: true,
};

module.exports = config;
```

Babel config `babel.config.js`:
```js
module.exports = api => {
  return {
    plugins: [
      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-proposal-object-rest-spread',
      [ 'formatjs', {
        ast: true,
        idInterpolationPattern: '[sha512:contenthash:base64:6]',
      } ],
    ],
    presets: [
      [ '@babel/preset-env', {
        modules: 'auto',
        targets: { node: 'current' },
      } ],
      '@babel/preset-react',
      '@babel/preset-typescript',
    ],
  };
};
```

Test example (.tsx):
```typescript jsx
import React from 'react';
import {
  IntlProvider,
  FormattedMessage,
} from 'react-intl';

import {
  render,
  screen,
} from '@testing-library/react';
import { defaultLocale } from 'common/hooks/useLocale';
import { consoleError } from 'utils/console';

test('[TSX] renders formatjs messages', () => {
  const onIntlError = (err: unknown) => {
    consoleError({ message: err });
  };

  const TestCmp = (
    <div>
      <IntlProvider
        locale={defaultLocale.language}
        messages={defaultLocale.locale}
        onError={onIntlError}
      >
        <div>
          <FormattedMessage
            defaultMessage={'Test text'}
            description={'Test intl message description'}
          />
        </div>
      </IntlProvider>
    </div>
  );

  render(TestCmp);
  screen.debug();
  expect(true).toBeTruthy(); // this line is irrelevant
});
```

`package.json`:
```json
{
  "name": "project",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@apollo/client": "^3.4.16",
    "@braintree/sanitize-url": "^6.0.0",
    "@garvae/react-pie-chart": "^1.1.4",
    "@graphql-codegen/introspection": "^2.1.0",
    "@popperjs/core": "^2.11.5",
    "@react-google-maps/api": "^2.2.0",
    "@reduxjs/toolkit": "^1.6.2",
    "@tippyjs/react": "^4.2.5",
    "apollo-link-scalars": "^3.0.0",
    "autosize": "^5.0.1",
    "axios": "^0.27.2",
    "babel-eslint": "^10.1.0",
    "clsx": "^1.1.1",
    "cross-fetch": "^3.1.5",
    "date-fns": "^2.16.1",
    "dayjs": "^1.10.7",
    "detect-touch-device": "^1.1.6",
    "draft-convert": "^2.1.12",
    "draft-js": "^0.11.7",
    "firebase": "^9.6.11",
    "focus-visible": "^5.2.0",
    "formik": "^2.2.9",
    "graphql": "^16.5.0",
    "graphql-scalars": "^1.13.6",
    "graphql-tag": "^2.12.5",
    "history": "^4.10.1",
    "immutability-helper": "^3.1.1",
    "libphonenumber-js": "^1.9.48",
    "lodash-es": "^4.17.15",
    "mime-types": "^2.1.35",
    "nuka-carousel": "^5.1.3",
    "path-to-regexp": "^6.2.0",
    "query-string": "^6.13.1",
    "react": "^17.0.2",
    "react-content-loader": "^6.0.3",
    "react-custom-scrollbars-2": "^4.4.0",
    "react-dnd": "^14.0.4",
    "react-dnd-html5-backend": "^14.0.2",
    "react-dnd-touch-backend": "^16.0.1",
    "react-dom": "^17.0.2",
    "react-dropzone": "^11.3.4",
    "react-error-boundary": "^3.1.4",
    "react-error-overlay": "6.0.9",
    "react-fast-compare": "^3.2.0",
    "react-helmet": "^6.1.0",
    "react-input-mask": "^2.0.4",
    "react-intl": "^5.21.2",
    "react-phone-input-2": "^2.14.0",
    "react-places-autocomplete": "^7.3.0",
    "react-player": "^2.9.0",
    "react-redux": "^7.2.5",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "~4.0.3",
    "react-spring": "^9.2.4",
    "react-table": "^7.7.0",
    "react-text-mask": "^5.4.3",
    "redux": "^4.1.1",
    "remove": "^0.1.5",
    "rrule": "^2.6.9",
    "rxjs": "^6.6.0",
    "sanitize.css": "^13.0.0",
    "sass": "^1.32.12",
    "subscriptions-transport-ws": "^0.11.0",
    "symbol-observable": "^3.0.0",
    "typescript": "^4.2.3",
    "use-debounce": "^7.0.1",
    "use-resize-observer": "^9.0.0",
    "uuid": "^8.3.2",
    "yup": "^0.32.9"
  },
  "scripts": {
    "test": "yarn generate:ts-config && jest"
  },
  "devDependencies": {
    "@babel/cli": "^7.17.0",
    "@babel/core": "^7.17.0",
    "@babel/eslint-parser": "^7.17.0",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-object-rest-spread": "^7.16.7",
    "@babel/plugin-proposal-optional-chaining": "^7.18.9",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-modules-commonjs": "^7.18.6",
    "@babel/plugin-transform-runtime": "^7.18.10",
    "@babel/preset-env": "^7.18.10",
    "@babel/preset-react": "^7.16.7",
    "@babel/preset-typescript": "^7.16.7",
    "@babel/runtime": "^7.18.9",
    "@formatjs/cli": "^4.4.0",
    "@formatjs/ts-transformer": "^3.9.9",
    "@getify/eslint-plugin-proper-arrows": "^11.0.3",
    "@getify/eslint-plugin-proper-ternary": "^3.1.1",
    "@graphql-codegen/cli": "^2.6.2",
    "@graphql-codegen/schema-ast": "^2.4.1",
    "@graphql-codegen/typescript": "^2.4.8",
    "@graphql-eslint/eslint-plugin": "^3.10.7",
    "@originate/eslint-plugin-ts-graphql": "^1.0.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^12.1.5",
    "@testing-library/user-event": "^14.4.3",
    "@types/async": "^3.2.15",
    "@types/autosize": "^4.0.0",
    "@types/date-fns": "^2.6.0",
    "@types/draft-convert": "^2.1.4",
    "@types/draft-js": "^0.11.5",
    "@types/jest": "26.0.14",
    "@types/lodash-es": "^4.17.3",
    "@types/mime-types": "^2.1.1",
    "@types/node": "^16.11.9",
    "@types/path-to-regexp": "^1.7.0",
    "@types/react": "^17.0.3",
    "@types/react-content-loader": "^4.0.0",
    "@types/react-dom": "^17.0.3",
    "@types/react-helmet": "^6.1.0",
    "@types/react-input-mask": "^3.0.1",
    "@types/react-places-autocomplete": "^7.2.8",
    "@types/react-redux": "^7.1.20",
    "@types/react-router": "^5.1.13",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-table": "^7.7.9",
    "@types/react-text-mask": "^5.4.11",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.33.0",
    "@typescript-eslint/parser": "^5.10.2",
    "babel-plugin-formatjs": "^10.3.25",
    "cpx": "^1.5.0",
    "cross-env": "^7.0.3",
    "customize-cra": "^1.0.0",
    "depcheck": "^1.4.3",
    "eslint-config-airbnb": "^19.0.1",
    "eslint-config-airbnb-typescript": "^16.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-plugin-array-func": "^3.1.7",
    "eslint-plugin-boundaries": "^2.8.0",
    "eslint-plugin-destructuring": "^2.2.1",
    "eslint-plugin-destructuring-newline": "^0.0.2",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-formatjs": "^4.1.0",
    "eslint-plugin-graphql": "^4.0.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jest": "^26.8.2",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-modules-newline": "^0.0.6",
    "eslint-plugin-newline-destructuring": "^1.0.1",
    "eslint-plugin-no-secrets": "^0.8.9",
    "eslint-plugin-no-unsanitized": "^4.0.1",
    "eslint-plugin-optimize-regex": "^1.2.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-sort-destructure-keys": "^1.4.0",
    "eslint-plugin-sort-keys-fix": "^1.1.2",
    "eslint-plugin-testing-library": "^5.0.5",
    "eslint-plugin-typescript-sort-keys": "^2.1.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "eslint-plugin-you-dont-need-lodash-underscore": "^6.12.0",
    "husky": "^7.0.1",
    "is-ci": "^3.0.0",
    "jest-environment-jsdom": "^26.6.2",
    "jest-transform-stub": "^2.0.0",
    "jest-transformer-svg": "^2.0.0",
    "lint-staged": "^12.3.7",
    "mjml": "^4.10.4",
    "pre-commit": "^1.2.2",
    "prepend": "^1.0.2",
    "prettier": "^2.2.1",
    "react-app-rewired": "^2.1.8",
    "react-verification-code-input": "^1.2.9",
    "rimraf": "^3.0.2",
    "scan-dir-recursive": "^1.0.11",
    "stylelint": "^13.12.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^21.0.0",
    "stylelint-high-performance-animation": "^1.5.2",
    "stylelint-no-unsupported-browser-features": "^4.1.4",
    "stylelint-order": "^4.1.0",
    "stylelint-scss": "^3.19.0",
    "svg-jest": "^1.0.1",
    "ts-jest": "26.5.6",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.9.1",
    "tslib": "^2.4.0",
    "webpack-bundle-analyzer": "^4.5.0"
  },
  "resolutions": {
    "@types/react": "17.0.2",
    "@types/react-dom": "17.0.2",
    "react-error-overlay": "6.0.9"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "eslint --fix"
    ],
    "*.{css,scss}": [
      "stylelint --fix --max-warnings=0",
      "prettier --write"
    ],
    "*.{json,md}": [
      "prettier --write"
    ]
  }
}
```

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": false,
    "target": "es5",
    "paths": {
      "app/*": ["./app/*"]
    }
  },
  "include": ["src"],
  "exclude": ["node_modules", "_other", "build", "coverage", "cache", "nginx", "**/*.spec.ts"]
}
```

## CodeSandbox

I made [codesandbox](https://codesandbox.io/s/great-cloud-81nr9w?file=/src/test.test.tsx), but an error there is about an "id" in the message. I don't know why, but it looks like the jest `astTransformers` config is not being applied in the [codesandbox](https://codesandbox.io/s/great-cloud-81nr9w?file=/src/test.test.tsx).

### Reproducible Steps

1. Create test (example above)
2. Add [additional config](https://formatjs.io/docs/tooling/ts-transformer/) to `jest.config.js`
3. Run tests

## Expected behavior
Expected to pass tests and get translated text:

> result example when using only babel config and `.jsx` tests
```text
√ renders formatjs messages (66 ms)

  console.log
    <body>
      <div>
        <div>
          <div>
            Test text
          </div>
        </div>
      </div>
    </body>

```

## Desktop
- OsName: Microsoft Windows 10 Pro
- OsVersion: 10.0.19043
- OsArchitecture: 64-bit
- Node: v16.15.0

## Additional context

I'm not sure if this is causing this problem, but when I tried searching for the problem I found this thing in
`node_modules/@formatjs/ts-transformer/ts-jest-integration.d.ts`:
```typescript
import { Opts } from '.';
//                 ↓ ↓ ↓ this type doesn't exists in "ts-jest/dist/types" ???
import type { TsCompilerInstance } from 'ts-jest/dist/types';
export declare const name = "@formatjs/ts-transformer";
export declare const version = "2.10.1";
export declare function factory(compilerInstance: TsCompilerInstance, opts: Opts): import("typescript").TransformerFactory<import("typescript").SourceFile>;
//# sourceMappingURL=ts-jest-integration.d.ts.map
```

<hr/>

P.S. Looks like something wrong in docs.

[Docs about babel.config.json](https://formatjs.io/docs/tooling/babel-plugin/#via-babelconfigjson-recommended):

**babel.config.json**
```json
{
  "plugins": [
    [
      "formatjs",
      {
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "ast": true
      }
    ]
  ]
}
```

[Docs about jest.config.js](https://formatjs.io/docs/tooling/ts-transformer/#via-ts-jest-in-jestconfigjs):

**jest.config.js**
```js
// jest.config.js
module.exports = {
  // [...]
  globals: {
    'ts-jest': {
      astTransformers: {
        before: [
          {
            path: '@formatjs/ts-transformer/ts-jest-integration',
            options: {
              // options
              overrideIdFn: '[sha512:contenthash:base64:6]',
              ast: true,
            },
          },
        ],
      },
    },
  },
}
```

Both configs use the "pattern" `[sha512:contenthash:base64:6]`.
In `babel.config.json` it is called `idInterpolationPattern`
but in `jest.config.js` it is called `overrideIdFn`. **I guess it's wrong**

And why don't you use something like `formatjs.config.js` in the ROOT 
to avoid multiple configs in different project's files?
In my project I have `formatjs` configs in:
- jest.config.js
- babel.config.json
- config-overrides.js (webpack)

**Comment by longlho** [comment]
Can you make a codesandbox pls

**Comment by garvae** [comment]
@longlho 

I made [codesandbox](https://codesandbox.io/s/great-cloud-81nr9w?file=/src/test.test.tsx), but an error there is about an "id" in the message. I don't know why, but it looks like the jest `astTransformers` config is not being applied in the [codesandbox](https://codesandbox.io/s/great-cloud-81nr9w?file=/src/test.test.tsx).

**Comment by garvae** [comment]
@longlho 

Ok, this is what I made locally to fix my issue:

`jest.config.js`
```js
module.exports.config = {
  globals: {
    /* ... */
    'ts-jest': {
      astTransformers: { before: [ {
          options: {
            ast: true,
            overrideIdFn: '[sha512:contenthash:base64:6]',
          },
          path: '<rootDir>/src/tests/ast-transformers/ts-jest-integration-fixed.js',
        } ] },
    /* ... */
    },
  },
}
```

`<rootDir>/src/tests/ast-transformers/ts-jest-integration-fixed.js`
```js
const _compilerModule = require('typescript');

const { factory: _factory } = require('@formatjs/ts-transformer/ts-jest-integration');

function factory(_, opts) {
  return _factory({ configSet: { compilerModule: _compilerModule } }, opts);
}

exports.factory = factory;
```

I added this "middleware" because when the original `factory` (`node_modules/@formatjs/ts-transformer/ts-jest-integration.js`) was called it doesn't get `configSet` in `compilerInstance`.

`node_modules/@formatjs/ts-transformer/ts-jest-integration.js`

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.factory = exports.version = exports.name = void 0;
var _1 = require(".");
exports.name = '@formatjs/ts-transformer';
exports.version = '2.10.1';
function factory(compilerInstance, opts) {
  /*                                                ↓↓↓ configSet is undefined  */
  return (0, _1.transformWithTs)(compilerInstance.configSet.compilerModule, opts);
}
exports.factory = factory;
```

**Comment by longlho** [comment]
@garvae wanna make a PR?

**Comment by garvae** [comment]
@longlho My solution is just a workaround. I don't know where the problem is in the code.
I'm just replacing the passed value by force-importing the typescript - this approach should not be in the `formatjs` library. This will mean that this library will have an additional dependency: `typescript`.
At the moment I don't have enough free time to find the problem. Maybe the problem might also be in `ts-jest`. If I have free time, I will return to this problem.

**Comment by longlho** [comment]
@garvae can you try latest version?

**Comment by ghost** [comment]
This is my error with jest after the upgrade

```bash
TypeError: Cannot read properties of undefined (reading 'kind')

      at Object.isStringLiteral (../../node_modules/.pnpm/ttypescript@1.5.13_typescript@4.7.4/node_modules/typescript/lib/typescript.js:28686:21)
      at isJestGlobalImport (../../node_modules/.pnpm/ts-jest@28.0.8_bi2kohzqnxavgozw3csgny5hju/node_modules/ts-jest/dist/transformers/hoist-jest.js:17:16)
      at ../../node_modules/.pnpm/ts-jest@28.0.8_bi2kohzqnxavgozw3csgny5hju/node_modules/ts-jest/dist/transformers/hoist-jest.js:71:29
          at Array.forEach (<anonymous>)
      at visitor (../../node_modules/.pnpm/ts-jest@28.0.8_bi2kohzqnxavgozw3csgny5hju/node_modules/ts-jest/dist/transformers/hoist-jest.js:69:43)
      at Object.visitNode (../../node_modules/.pnpm/ttypescript@1.5.13_typescript@4.7.4/node_modules/typescript/lib/typescript.js:89314:23)
      at ../../node_modules/.pnpm/ts-jest@28.0.8_bi2kohzqnxavgozw3csgny5hju/node_modules/ts-jest/dist/transformers/hoist-jest.js:96:23
      at transformSourceFileOrBundle (../../node_modules/.pnpm/ttypescript@1.5.13_typescript@4.7.4/node_modules/typescript/lib/typescript.js:90654:68)
      at transformation (../../node_modules/.pnpm/ttypescript@1.5.13_typescript@4.7.4/node_modules/typescript/lib/typescript.js:109638:24)
      at transformRoot (../../node_modules/.pnpm/ttypescript@1.5.13_typescript@4.7.4/node_modules/typescript/lib/typescript.js:109665:82)
```

**Comment by joshuambg** [comment]
I can also confirm this problem. I'm experiencing the same issues as the OP. I think he did an excellent job outlining the problem.

The package authors need to fix this in the next release. Everything should be available to them in this issue to identify the problem. Good luck! Hurry up. Thanks.

EDIT: Confirmed the issue seems introduced in version `@formatjs/ts-transformer@3.4.0`

**Comment by longlho** [comment]
Until there's a codesandbox to repro we won't be able to do anything

**Comment by ghost** [comment]
I'm in Typescript version "typescript": "^4.7.4" and seems upgrading to latest fix the issue. But as for the changeling it says it works in typescript 4.7
