### ISSUE TITLE
[swc-plugin] Method visitTsType not implemented (still broken after fix)

### ISSUE THREAD

**Issue by srmagura** [formatjs/formatjs#3782]
## Which package?
swc-plugin

## Describe the bug
The swc plugin fails to compile the TypeScript code

```ts
const w = window as any;
```

with the error

```
/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:1265
        throw new Error("Method visitTsType not implemented.");
              ^

Error: Method visitTsType not implemented.
    at FormatJSTransformer.visitTsType (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:1265:15)
    at FormatJSTransformer.visitTsAsExpression (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:903:33)
    at FormatJSTransformer.visitExpression (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:815:29)
    at FormatJSTransformer.visitOptionalExpression (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:198:25)
    at FormatJSTransformer.visitVariableDeclarator (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:419:23)
    at Array.map (<anonymous>)
    at FormatJSTransformer.visitVariableDeclarators (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:415:22)
    at FormatJSTransformer.visitVariableDeclaration (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:411:31)
    at FormatJSTransformer.visitDeclaration (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:407:29)
    at FormatJSTransformer.visitStatement (/Users/srmagura/Documents/oss/formatjs-swc-repro/node_modules/@swc/core/Visitor.js:232:29)
```

Original issue here: https://github.com/formatjs/formatjs/issues/3690. I'm not sure if this is a regression or if it was never fully fixed in the first place.

## To Reproduce

Minimal repro: https://github.com/srmagura/formatjs-swc-repro

### Codesandbox URL

I'm not sure if it's possible to use swc in CodeSandbox.

### Reproducible Steps/Repo

Clone the minimal repro and run `yarn`, then `yarn build`.

## Expected behavior

The code is compiled without error.

## Desktop (please complete the following information):

macOS 12.5.1

**Comment by longlho** [comment]
this is bc of https://github.com/swc-project/swc/issues/4648 so closing this

**Comment by srmagura** [comment]
Thanks @longlho. Is there any workaround in the meantime? It seems like this flaw in swc makes `@formatjs/swc-plugin` unusable with TypeScript — unless I am missing something obvious.

**Comment by longlho** [comment]
unfortunately u'll likely have to use some tool to stripe TS types it looks like
