### ISSUE TITLE
@formatjs/ts-transformer breaks build after the upgrade

### ISSUE THREAD

**Issue by ghost** [formatjs/formatjs#3783]
## Which package?
@formatjs/ts-transformer

## Describe the bug
After upgrade to latest version following error throw when try to build the project.

```bash
/Users/Project/node_modules/typescript/lib/typescript.js:117612
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at isOuterExpression (/Users/Project/node_modules/typescript/lib/typescript.js:29925:22)
    at Object.skipOuterExpressions (/Users/Project/node_modules/typescript/lib/typescript.js:29944:16)
    at Object.skipPartiallyEmittedExpressions (/Users/Project/node_modules/typescript/lib/typescript.js:13316:19)
    at Object.parenthesizeExpressionOfExportDefault (/Users/Project/node_modules/typescript/lib/typescript.js:21788:28)
    at createExportAssignment (/Users/Project/node_modules/typescript/lib/typescript.js:25487:40)
    at Object.updateExportAssignment (/Users/Project/node_modules/typescript/lib/typescript.js:25497:26)
    at Object.visitEachChild (/Users/Project/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:91123:32)
    at visitor (/Users/Project/node_modules/.pnpm/@formatjs+ts-transformer@3.10.0_ts-jest@28.0.8/node_modules/@formatjs/ts-transformer/src/transform.js:444:19)
    at visitArrayWorker (/Users/Project/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:90614:48)
    at visitNodes (/Users/Project/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:90577:23)
```

## To Reproduce

1. Setup a react project with ttypescript to do the transformation.2. 
2. Upgrade @formatjs/ts-transformer to `^3.10.0`. 
3. Run `ttsc -b .` .

## Expected behavior
To transform and build the project without issues.

## Desktop (please complete the following information):

- OS: [e.g. MacOS]
- Version [e.g. ^3.10.0]
- Node 16.x

**Comment by longlho** [comment]
Is there a codesandbox?

**Comment by gwer** [comment]
I'm pretty sure the problem is `typescript` in package's dependencies list. And in last version of `@formatjs/ts-transformer` the `typescript` was updated. 

I got a broken build too after installing `babel-plugin-formatjs` (`@formatjs/ts-transformer` is in its dependencies).

The reason is two installed versions of TS (I also have TS in my project of course) and conflict between them.

I fixed it by updating typescript in my project to the same version (`yarn add --dev typescript@^4.7`), but it's just a workaround. If I install another package with the same dependency management approach, I have a chance of never fixing the project.

I think it's not correct to add `typescript` to the library dependencies. Perhaps it should be in peerDependencies/devDependencies section.

**Comment by longlho** [comment]
no we do need to specify `typescript` version as dep because we depend on its API and AST which primarily have breaking changes in minor versions

**Comment by ghost** [comment]
I got typescript ^4.7.4 and seems upgrading to 4.8.x fixes this.

**Comment by gwer** [comment]
> no we do need to specify typescript version as dep because we depend on its API and AST which primarily have breaking changes in minor versions

So why do you use `^4.7` version notation which doesn't guarantee minor version? Just now `yarn add @formatjs/ts-transformer` installs `typescript@4.8.2`.

This is especially funny because there was `4.7.4` in my project. But yarn has its own way :-D

If you're worried about minor version compatibility you might need `~4.7` in `package.json`. 

And then it's very important to write in documentation about compatible versions of `typescript` and `formatjs` packages. Because there are huge number of packages in npm, and if somebody needs to install something else with the same typescript dependency versioning strategy this can lead to unresolvable conflicts.

**Comment by longlho** [comment]
It can have breaking changes in minor versions but not all the time. We just know it worked for 4.7 and not 4.6 and we don't know if it's gonna work for 4.9 or 4.10 until someone reports it. It's unlikely to work for 5.0, thus ^4.7.
