### ISSUE TITLE
Typescript 5 support - context.factory.updateIdentifier is not a function

### ISSUE THREAD

**Issue by damiangreen** [formatjs/formatjs#3984]
## Which package?
@formatjs+ts-transformer 3.11.6

## Describe the bug
When Using Typescript 5 beta

```
TypeError: context.factory.updateIdentifier is not a function
    at visitEachChildOfIdentifier (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91548:36)
    at Object.visitEachChild (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91541:42)
    at visitor (app\node_modules\.pnpm\@formatjs+ts-transformer@3.11.6_ts-jest@28.0.7\node_modules\@formatjs\ts-transformer\src\transform.js:444:19)
    at visitNode (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91309:23)
    at visitEachChildOfImportClause (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91883:78)
    at Object.visitEachChild (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91541:42)
    at visitor (app\node_modules\.pnpm\@formatjs+ts-transformer@3.11.6_ts-jest@28.0.7\node_modules\@formatjs\ts-transformer\src\transform.js:444:19)
    at visitNode (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91309:23)
    at visitEachChildOfImportDeclaration (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91874:120)
    at Object.visitEachChild (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91541:42)
    at visitor (app\node_modules\.pnpm\@formatjs+ts-transformer@3.11.6_ts-jest@28.0.7\node_modules\@formatjs\ts-transformer\src\transform.js:444:19)
    at visitArrayWorker (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91397:48)
    at visitNodes (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91361:23)
    at visitLexicalEnvironment (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91427:22)
    at visitEachChildOfSourceFile (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91970:59)
    at Object.visitEachChild (app\node_modules\.pnpm\typescript@4.9.4\node_modules\typescript\lib\typescript.js:91541:42)
    ```
    It appears to have a dependency on an old version of typescript

## To Reproduce

Install TS 5 beta
### Reproducible Steps/Repo

In jest.config 
```
 'ts-jest': {
      isolatedModules: true,
      astTransformers: {
        before: [
          {
            path: '@formatjs/ts-transformer/ts-jest-integration',
            options: {
              overrideIdFn: '[sha512:contenthash:base64:6]',
              ast: true,
              preserveWhitespace: true,
            },
          },
        ],
      },
    },
    ```

## Desktop (please complete the following information):

- OS: Win 11
- N/a
- Latest

**Comment by kulaeff** [comment]
I also ran into this issue. Any solutions except downgrading typescript version?

**Comment by LuisUrrutia** [comment]
Same error
