### ISSUE TITLE
[@formatjs/intl-durationformat] package.json deprecation warning

### ISSUE THREAD

**Issue by Crisfole** [formatjs/formatjs#4354]
## Which package?

`@formatjs/intl-durationformat`

## Describe the bug

The code works well, but triggers a deprecation notice regarding your package configuration in package.json:

```
(node:95506) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/me/reponame/node_modules/@formatjs/intl-durationformat/package.json' of 'index.umd.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:411:15)
    at Module._findPath (node:internal/modules/cjs/loader:613:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at a._resolveFilename (/home/me/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/cjs/index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/me/reponame/node_modules/@formatjs/intl-durationformat/polyfill.js:3:10)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.S (/home/me/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/cjs/index.cjs:1:1292)
```

### Codesandbox URL

Don't have an account, the below is very actionable, though.

### Reproducible Steps/Repo

1. `mkdir deprecation-demo && cd deprecation-demo`
2. `nvm use v18.12.1` # Install first if necessary
3. `npm init -y && npm install temporal-polyfill @formatjs/intl-durationformat`
4. Execute the following to create the demo file:
   ```sh
   cat <<DEMOJS > demo.mjs
   import { Temporal } from 'temporal-polyfill';
   import '@formatjs/intl-durationformat/polyfill.js';
   
   const d = Temporal.Duration.from('P1DT6H30M');
   console.log(d.toLocaleString()); // example output: '1 day, 6 hr, 30 min'
   console.log(d.toLocaleString('de-DE')); // example output: '1 Tg., 6 Std. und 30 Min.'
   console.log(d.toLocaleString('es')); // example output: '1 d, 6 h, 30 min'
   console.log(d.toLocaleString('en-US', { day: 'numeric', hour: 'numeric' })); // example output: '1 d, 6 
   h, 30 min'
   DEMOJS
   ```
6. Run the demo file: `node demo.mjs`
7. Notice that the file prints delightfully localized time periods in English, German, Spanish, English again, and a nice big ugly Deprecation warning at the end.

## Expected behavior

I expect the import to work without triggering a deprecation notice.

## Screenshots

Unnecsesary

## Desktop (please complete the following information):

- OS: Ubuntu under WSL on Windows 11
- Browser: N/A
- Version: N/A

## Smartphone (please complete the following information):

N/A

## Additional context

This is a Node problem. It is reproducible with `tsx` as well as `npx`

**Comment by Crisfole** [comment]
I'll add that this must have something to do with the build process since the package.json in intl-durationformat does not _have_ a `main` field. That means I suspect this affects your other packages just as much as this one.

**Comment by longlho** [comment]
fixed in latest
