### ISSUE TITLE
Website: Uncaught ReferenceError in main js bundle breaking website functionality

### ISSUE THREAD

**Issue by emma-sg** [formatjs/formatjs#4772]
I'm seeing errors and am unable to use any of the portions of the website that use javascript, including switching between tabs in documentation, using search, opening the mobile navigation, and using the demo on the homepage. Tested in latest Chrome, Safari, and Firefox on latest macOS.

Error:
```
main.7e949d58.js:2 Uncaught ReferenceError: exports is not defined
    at 9378 (main.7e949d58.js:2:1172708)
    at b (runtime~main.d4245360.js:1:136)
    at 4404 (main.7e949d58.js:2:1137195)
    at b (runtime~main.d4245360.js:1:136)
    at 9037 (main.7e949d58.js:2:6722)
    at b (runtime~main.d4245360.js:1:136)
    at main.7e949d58.js:2:1764002
    at b.O (runtime~main.d4245360.js:1:424)
    at main.7e949d58.js:2:1764022
    at a (runtime~main.d4245360.js:1:5742)
```

This appears on the homepage and on any other page with interactive content.

Digging into this a little, it looks like it may be coming from or related to the `@orama/plugin-docusaurus-v3` package?

**Comment by longlho** [comment]
cc @ilteoood do you if anything's changed on the Orama side?

**Comment by ilteoood** [comment]
Maybe the plugin has been updated to a version that has a bug.
I think there should be another version that fixes this

**Comment by longlho** [comment]
Hmm we have renovate auto update things so it should basically always be at the latest. Let me manually bump it.

**Comment by longlho** [comment]
yup still broken :( even though https://github.com/formatjs/formatjs/pull/4779 is merged

**Comment by devolod** [comment]
The same error:
![image](https://github.com/user-attachments/assets/c14462ac-bbf5-47e8-baa1-1a3649420b71)

**Comment by alexkrautmann** [comment]
It seems like all interactive JS on the docs website is broken?

- https://github.com/formatjs/formatjs/issues/4842
- https://github.com/formatjs/formatjs/issues/4827
- https://github.com/formatjs/formatjs/issues/4812

I also notice that I can't click on the theme switcher or "Search" button.

https://github.com/user-attachments/assets/db5e22f5-571a-4232-86f5-abe9dc5c30b7

**Comment by longlho** [comment]
yup I'm working on fixing it

**Comment by longlho** [comment]
fixed in latest
